runtime: nodejs18

handlers:
  - url: /static
    static_dir: static

  - url: /.*
    script: index.js

env_variables:
  PORT_NUMBER: 8080
  APP_ROUTE: https://speelingbee-backend-dot-speelingbee.uc.r.appspot.com